name: decision-transformer-gym
channels:
- pytorch
dependencies:
- python=3.8
- anaconda
- cudatoolkit=11.6
- numpy
- pip
- pip:
  - gym==0.23.1
  - torch==1.13.1
  - transformers
  - wandb==0.9.1
  - numpy
  - mujoco-py
